data<- read.table(file = household_power_consumption.txt, sep = ";", header= TRUE, StringsAsFactors = FALSE)
df<- subset(data, Date =="1/2/2007"| Date == "2/2/2007")
df$DateTime <- strptime(paste(df$Date, df$Time), format="%d/%m/%Y %H:%M:%S")
class(df$DateTime)
library(lubridate)
summary(wday(df$DateTime, label=TRUE))
df$Global_active_power <- as.numeric(df$Global_active_power)
title(main="Global Active Power")
hist(df$Global_active_power, main= "Global Active Power", col= "red",xlab="Global Active Power (kilowatts)")
df$Sub_metering_1 <- as.numeric(df$Sub_metering_1)
df$Sub_metering_2 <- as.numeric(df$Sub_metering_2)
df$Sub_metering_3 <- as.numeric(df$Sub_metering_3)
df$Voltage <- as.numeric(df$Voltage)
#after defining variables as numeric
par(mfrow = c(2, 2)) 
plot(df$DateTime, df$Global_active_power, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(df$DateTime, df$Voltage, type="l", xlab="datetime", ylab="Voltage", cex= 0.2)
plot(df$DateTime, df$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(df$DateTime, df$Sub_metering_2, type="l", col="red")
lines(df$DateTime, df$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"), bty="o", cex=0.5)
plot(df$DateTime, df$Global_active_power, type="l", xlab="datetime", ylab="Global_reactive_power")