data<- read.table(file = household_power_consumption.txt, sep = ";", header= TRUE, StringsAsFactors = FALSE)
df<- subset(data, Date =="1/2/2007"| Date == "2/2/2007")
df$DateTime <- strptime(paste(df$Date, df$Time), format="%d/%m/%Y %H:%M:%S")
class(df$DateTime)
library(lubridate)
summary(wday(df$DateTime, label=TRUE))
df$Global_active_power <- as.numeric(df$Global_active_power)
title(main="Global Active Power")
hist(df$Global_active_power, main= "Global Active Power", col= "red",xlab="Global Active Power (kilowatts)")